use chrono::Local;
use regex::Regex;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::{collections::{HashMap, HashSet}, fs, io::Write, path::{Path, PathBuf}, process::Command, time::{Duration, Instant}};
use tauri::Manager;
use windows_sys::Win32::{Foundation::{CloseHandle, INVALID_HANDLE_VALUE}, System::Diagnostics::ToolHelp::{CreateToolhelp32Snapshot, Process32FirstW, Process32NextW, PROCESSENTRY32W, TH32CS_SNAPPROCESS}};

type AppResult<T> = Result<T, String>;

#[derive(Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
struct ReasoningConfig { levels: Vec<String>, default_level: String }

#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Provider { id: String, name: String, model: String, url: String, protocol: String, #[serde(default)] models: Vec<String>, #[serde(default)] reasoning_by_model: HashMap<String, ReasoningConfig>, #[serde(default)] api_key: String }

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ProviderView { id: String, name: String, model: String, url: String, protocol: String, models: Vec<String>, reasoning_by_model: HashMap<String, ReasoningConfig>, has_api_key: bool }
impl From<&Provider> for ProviderView { fn from(p: &Provider) -> Self { Self { id:p.id.clone(), name:p.name.clone(), model:p.model.clone(), url:p.url.clone(), protocol:p.protocol.clone(), models:p.models.clone(), reasoning_by_model:p.reasoning_by_model.clone(), has_api_key:!p.api_key.is_empty() } } }

#[derive(Clone, Serialize, Deserialize)]
struct Account {
    #[serde(alias = "Id")]
    id: String,
    #[serde(alias = "Name")]
    name: String,
}
#[derive(Serialize)] #[serde(rename_all = "camelCase")] struct AccountView { id: String, name: String, logged_in: bool }
#[derive(Clone, Serialize, Deserialize)] #[serde(rename_all = "camelCase")] struct LaunchRecord { pid: u32, label: String }
#[derive(Serialize)] #[serde(rename_all = "camelCase")] struct RuntimeStatus { state: String, label: String, detail: String }
#[derive(Serialize)] #[serde(rename_all = "camelCase")] struct AppData { providers: Vec<ProviderView>, accounts: Vec<AccountView>, runtime_status: RuntimeStatus, recent_logs: Vec<String>, config_dir: String, profiles_dir: String, logs_dir: String }
#[derive(Clone, Serialize)] #[serde(rename_all = "camelCase")] struct UsageWindow { remaining_percent: f64, resets_at: Option<i64> }
#[derive(Clone, Serialize)] #[serde(rename_all = "camelCase")] struct UsageProfile { scope: String, label: String, source: String, primary: Option<UsageWindow>, secondary: Option<UsageWindow>, reset_credits: u32, plan_type: Option<String>, error: Option<String> }
#[allow(dead_code)] #[derive(Clone, Deserialize)] #[serde(rename_all = "camelCase")] struct CliProxyInput { base_url: String, management_key: String }
#[derive(Deserialize)] #[serde(rename_all = "camelCase")] struct SaveProviderInput { id: String, name: String, model: String, url: String, protocol: String, api_key: Option<String>, models: Vec<String>, reasoning_by_model: HashMap<String, ReasoningConfig>, original_id: Option<String> }

fn local_data() -> AppResult<PathBuf> { std::env::var_os("LOCALAPPDATA").map(PathBuf::from).ok_or("无法读取 LOCALAPPDATA".into()) }
fn config_dir() -> AppResult<PathBuf> { Ok(local_data()?.join("JetBrains").join("CodexIdeaHome")) }
fn profiles_dir() -> AppResult<PathBuf> { Ok(local_data()?.join("JetBrains").join("CodexIdeaProfiles")) }
fn logs_dir() -> AppResult<PathBuf> { Ok(config_dir()?.join("logs")) }
fn providers_path() -> AppResult<PathBuf> { Ok(config_dir()?.join("ci-providers.json")) }
fn accounts_path() -> AppResult<PathBuf> { Ok(profiles_dir()?.join("openai-accounts.json")) }
fn config_path() -> AppResult<PathBuf> { Ok(config_dir()?.join("config.toml")) }
fn catalog_path() -> AppResult<PathBuf> { Ok(config_dir()?.join("ci-model-catalog.json")) }
fn launch_record_path() -> AppResult<PathBuf> { Ok(config_dir()?.join("idea-launch-record.json")) }
fn stamp() -> String { Local::now().format("%Y%m%d-%H%M%S-%3f").to_string() }
fn escape(s: &str) -> String { s.replace('\\', "\\\\").replace('"', "\\\"") }
fn redact(s:&str)->String { Regex::new(r#"(?i)(bearer\s+|api[_-]?key[\"']?\s*[:=]\s*[\"']?)[^\s\"',;}]+"#).map(|r|r.replace_all(s,"$1[REDACTED]").into_owned()).unwrap_or_else(|_|s.into()) }
fn log_entry(kind:&str,message:&str){if let Ok(dir)=logs_dir(){let _=fs::create_dir_all(&dir);let path=dir.join(format!("ci-{}.log",Local::now().format("%Y-%m-%d")));let line=format!("[{}] [{}]\r\n{}\r\n\r\n",Local::now().format("%Y-%m-%d %H:%M:%S%.3f %:z"),kind,redact(message));if let Ok(mut f)=fs::OpenOptions::new().create(true).append(true).open(path){let _=f.write_all(line.as_bytes());}}}
fn backup(path:&Path)->AppResult<()> { if path.exists(){fs::copy(path,format!("{}.backup-{}",path.display(),stamp())).map_err(|e|format!("创建备份失败：{e}"))?;} Ok(()) }
fn atomic_write(path:&Path,text:&str)->AppResult<()> {if let Some(dir)=path.parent(){fs::create_dir_all(dir).map_err(|e|e.to_string())?;}let tmp=path.with_extension("ci.tmp");fs::write(&tmp,text.as_bytes()).map_err(|e|e.to_string())?;fs::rename(tmp,path).map_err(|e|e.to_string())}
fn read_json<T:for<'a>Deserialize<'a>+Default>(p:&Path)->T{fs::read_to_string(p).ok().and_then(|s|serde_json::from_str(&s).ok()).unwrap_or_default()}
fn auth_account_id(value:&Value)->Option<String>{value.get("tokens").and_then(|v|v.get("account_id")).or_else(||value.get("account_id")).and_then(Value::as_str).filter(|v|!v.trim().is_empty()).map(str::to_owned)}
fn auth_account_id_at(path:&Path)->Option<String>{fs::read_to_string(path).ok().and_then(|text|serde_json::from_str::<Value>(&text).ok()).and_then(|value|auth_account_id(&value))}
fn base64url_decode(value:&str)->Option<Vec<u8>>{let mut output=Vec::new();let mut bits=0u32;let mut count=0;for byte in value.bytes(){let part=match byte{b'A'..=b'Z'=>byte-b'A',b'a'..=b'z'=>byte-b'a'+26,b'0'..=b'9'=>byte-b'0'+52,b'-'=>62,b'_'=>63,_=>return None};bits=(bits<<6)|part as u32;count+=6;while count>=8{count-=8;output.push((bits>>count)as u8);bits&=(1<<count)-1;}}Some(output)}
fn auth_display_name(value:&Value)->Option<String>{let claims=value.get("tokens").and_then(|tokens|tokens.get("id_token")).and_then(Value::as_str).and_then(|token|token.split('.').nth(1)).and_then(base64url_decode).and_then(|bytes|serde_json::from_slice::<Value>(&bytes).ok());claims.and_then(|claims|claims.get("email").or_else(||claims.get("name")).and_then(Value::as_str).filter(|name|!name.trim().is_empty()).map(str::to_owned).or_else(||auth_account_id(value).map(|id|format!("账号 {}",&id[..id.len().min(8)]))))}
fn auth_display_name_at(path:&Path)->Option<String>{fs::read_to_string(path).ok().and_then(|text|serde_json::from_str::<Value>(&text).ok()).and_then(|value|auth_display_name(&value))}
fn default_codex_home()->Option<PathBuf>{std::env::var_os("USERPROFILE").map(PathBuf::from).map(|path|path.join(".codex"))}
#[allow(dead_code)] fn app_server_request(_: &Path, _: &str, _: Value)->AppResult<Value>{Err("旧版 app-server 额度路径已停用。".into())}

fn usage_window(value:Option<&Value>)->Option<UsageWindow>{let value=value?;let used=value.get("usedPercent").or_else(||value.get("used_percent"))?.as_f64()?;Some(UsageWindow{remaining_percent:(100.0-used).clamp(0.0,100.0),resets_at:value.get("resetsAt").or_else(||value.get("reset_at")).and_then(Value::as_i64)})}
fn usage_window_seconds(value:&Value)->Option<u64>{value.get("limitWindowSeconds").or_else(||value.get("limit_window_seconds")).and_then(Value::as_u64)}
fn usage_windows(snapshot:Option<&Value>)->(Option<UsageWindow>,Option<UsageWindow>){
 let Some(snapshot)=snapshot else{return(None,None)};
 let values=[snapshot.get("primary").or_else(||snapshot.get("primary_window")),snapshot.get("secondary").or_else(||snapshot.get("secondary_window"))];
 let mut five_hour=None;
 let mut weekly=None;
 let mut unknown=Vec::new();
 for value in values.into_iter().flatten(){
  let Some(window)=usage_window(Some(value))else{continue};
  match usage_window_seconds(value){
   Some(18_000)=>five_hour=Some(window),
   Some(604_800)=>weekly=Some(window),
   _=>unknown.push(window),
  }
 }
 if five_hour.is_none()&&!unknown.is_empty(){five_hour=Some(unknown.remove(0))}
 if weekly.is_none()&&!unknown.is_empty(){weekly=Some(unknown.remove(0))}
 (five_hour,weekly)
}
fn available_credits(result:&Value)->u32{result.get("rateLimitResetCredits").and_then(|v|v.get("availableCount")).and_then(Value::as_u64).or_else(||result.get("credits").and_then(Value::as_array).map(|items|items.iter().filter(|item|item.get("status").and_then(Value::as_str)==Some("available")).count() as u64)).unwrap_or(0) as u32}
fn usage_profile(scope:String,label:String,source:&str,result:Value,credits:Option<Value>)->UsageProfile{let snapshot=result.get("rateLimitsByLimitId").and_then(|v|v.get("codex")).or_else(||result.get("rateLimits")).or_else(||result.get("rate_limit"));let credit_source=credits.as_ref().unwrap_or(&result);let(primary,secondary)=usage_windows(snapshot);UsageProfile{scope,label,source:source.into(),primary,secondary,reset_credits:available_credits(credit_source),plan_type:snapshot.and_then(|v|v.get("planType").or_else(||v.get("plan_type"))).and_then(Value::as_str).map(str::to_owned),error:None}}
fn usage_error(scope:String,label:String,source:&str,error:String)->UsageProfile{UsageProfile{scope,label,source:source.into(),primary:None,secondary:None,reset_credits:0,plan_type:None,error:Some(error)}}
fn profile_home(scope:&str)->AppResult<(PathBuf,String)>{if scope=="default"{let home=default_codex_home().ok_or("无法读取默认 Codex 目录。")?;if !home.join("auth.json").exists(){return Err("默认 Codex 登录态不存在。".into())}return Ok((home,"默认 Codex 登录态".into()))}let account=load_accounts()?.into_iter().find(|a|a.id==scope).ok_or("账号不存在。")?;let home=profiles_dir()?.join(&account.id);if !home.join("auth.json").exists(){return Err("该账号尚未登录或导入认证。".into())}Ok((home,format!("OpenAI · {}",account.name)))}
#[allow(dead_code)] fn local_usage_limits()->AppResult<Vec<UsageProfile>>{let accounts=load_accounts()?;let mut candidates=vec![];if let Some(home)=default_codex_home(){if home.join("auth.json").exists(){candidates.push(("default".to_string(),"默认 Codex 登录态".to_string(),home))}}for account in accounts{let home=profiles_dir()?.join(&account.id);if home.join("auth.json").exists(){candidates.push((account.id,format!("OpenAI · {}",account.name),home))}}let mut seen=HashSet::new();let mut profiles=vec![];for (scope,label,home) in candidates{match app_server_request(&home,"account/rateLimits/read",json!({"excludeResetCreditDetails":false,"supportsLunaReserve":false})){Ok(result)=>{let account_id=result.get("accountId").and_then(Value::as_str).unwrap_or(&scope).to_owned();if seen.insert(account_id){profiles.push(usage_profile(scope,label,"local",result,None));}},Err(error)=>profiles.push(usage_error(scope,label,"local",error))}}if profiles.is_empty(){return Err("没有已登录的本机 Codex 账号可查询。".into())}Ok(profiles)}
#[cfg(any())] mod unused_proxy_adapter { use super::*;
fn proxy_base(input:&CliProxyInput)->AppResult<String>{let url=reqwest::Url::parse(input.base_url.trim()).map_err(|_|"CLIProxyAPI 地址必须是有效的 http/https URL。")?;if !matches!(url.scheme(),"http"|"https"){return Err("CLIProxyAPI 地址仅支持 http 或 https。".into())}if input.management_key.trim().is_empty(){return Err("请输入 CLIProxyAPI 管理密钥。".into())}Ok(input.base_url.trim_end_matches('/').to_string())}
fn proxy_request(input:&CliProxyInput,path:&str,body:Option<Value>)->AppResult<Value>{let base=proxy_base(input)?;let client=reqwest::blocking::Client::builder().timeout(Duration::from_secs(20)).build().map_err(|e|format!("创建 CLIProxyAPI 连接失败：{e}"))?;let request=client.post(format!("{base}/v0/management/{path}")).header("Authorization",format!("Bearer {}",input.management_key));let response=match body{Some(body)=>request.json(&body).send(),None=>client.get(format!("{base}/v0/management/{path}")).header("Authorization",format!("Bearer {}",input.management_key)).send()}.map_err(|_|"无法连接 CLIProxyAPI，请检查地址、服务状态和网络。")?;if !response.status().is_success(){return Err(format!("CLIProxyAPI 管理接口返回 HTTP {}。",response.status()))}response.json::<Value>().map_err(|_|"CLIProxyAPI 返回了无法解析的数据。".into())}
fn proxy_api_call(input:&CliProxyInput,auth_index:&str,method:&str,url:&str,header:Value,data:Option<Value>)->AppResult<Value>{let mut payload=json!({"auth_index":auth_index,"method":method,"url":url,"header":header});if let Some(data)=data{payload["data"]=Value::String(data.to_string())}let response=proxy_request(input,"api-call",Some(payload))?;let status=response.get("status_code").and_then(Value::as_u64).unwrap_or(500);if !(200..300).contains(&status){return Err(format!("账号额度服务返回 HTTP {status}。"))}let body=response.get("body").and_then(Value::as_str).ok_or("CLIProxyAPI 额度响应缺少数据。")?;serde_json::from_str(body).map_err(|_|"额度服务返回了无法解析的数据。".into())}
fn value_text(value:&Value,keys:&[&str])->Option<String>{keys.iter().find_map(|key|value.get(*key).and_then(Value::as_str).map(str::trim).filter(|value|!value.is_empty()).map(str::to_owned))}
fn proxy_header(auth:&Value)->Value{let mut header=json!({"Authorization":"Bearer $TOKEN$","Content-Type":"application/json","User-Agent":"Codex Idea Tool"});if let Some(account)=value_text(auth,&["account_id","accountId","chatgpt_account_id"]){header["Chatgpt-Account-Id"]=Value::String(account)}header}
fn is_codex_auth(auth:&Value)->bool{["type","provider","channel","platform","name","filename"].iter().filter_map(|key|value_text(auth,&[*key])).any(|value|value.to_ascii_lowercase().contains("codex"))}
fn cli_proxy_usage_limits(input:&CliProxyInput)->AppResult<Vec<UsageProfile>>{let records=proxy_request(input,"auth-files",None)?;let records=records.as_array().or_else(||records.get("auth_files").and_then(Value::as_array)).ok_or("CLIProxyAPI 认证文件响应格式不受支持。")?;let mut profiles=vec![];for auth in records.iter().filter(|auth|is_codex_auth(auth)){let Some(index)=value_text(auth,&["auth_index","authIndex"])else{continue};let label=value_text(auth,&["email","account","name","id","filename"]).unwrap_or_else(||format!("Codex · {index}"));let header=proxy_header(auth);let scope=format!("cliproxy:{index}");match (proxy_api_call(input,&index,"GET","https://chatgpt.com/backend-api/wham/usage",header.clone(),None),proxy_api_call(input,&index,"GET","https://chatgpt.com/backend-api/wham/rate-limit-reset-credits",header,None)){(Ok(usage),Ok(credits))=>profiles.push(usage_profile(scope,label,"cliproxy",usage,Some(credits))),(Err(error),_)|(_,Err(error))=>profiles.push(usage_error(scope,label,"cliproxy",error))}}if profiles.is_empty(){return Err("CLIProxyAPI 中没有可查询的 Codex OAuth 账号。".into())}Ok(profiles)}
fn reset_proxy_usage(input:&CliProxyInput,scope:&str)->AppResult<String>{let index=scope.strip_prefix("cliproxy:").ok_or("无效的 CLIProxyAPI 账号。")?;let records=proxy_request(input,"auth-files",None)?;let records=records.as_array().or_else(||records.get("auth_files").and_then(Value::as_array)).ok_or("CLIProxyAPI 认证文件响应格式不受支持。")?;let auth=records.iter().find(|auth|value_text(auth,&["auth_index","authIndex"]).as_deref()==Some(index)).ok_or("CLIProxyAPI 中未找到该账号。")?;let label=value_text(auth,&["email","account","name","id","filename"]).unwrap_or_else(||format!("Codex · {index}"));let header=proxy_header(auth);let credits=proxy_api_call(input,index,"GET","https://chatgpt.com/backend-api/wham/rate-limit-reset-credits",header.clone(),None)?;let credit=credits.get("credits").and_then(Value::as_array).and_then(|credits|credits.iter().find(|credit|credit.get("status").and_then(Value::as_str)==Some("available"))).and_then(|credit|credit.get("id")).and_then(Value::as_str).ok_or("当前账号没有可用的额度重置次数。")?;let _=proxy_api_call(input,index,"POST","https://chatgpt.com/backend-api/wham/rate-limit-reset-credits/consume",header,json!({"credit_id":credit,"redeem_request_id":uuid::Uuid::new_v4().to_string()}).into())?;let _=proxy_request(input,"reset-quota",Some(json!({"auth_index":index})))?;log_entry("USAGE RESET",&format!("已通过 CLIProxyAPI 为“{}”提交一次额度重置。",label));Ok(format!("已为“{}”提交额度重置，正在刷新最新额度。",label))}
#[tauri::command] fn legacy_load_usage_limits(cli_proxy:Option<CliProxyInput>)->AppResult<Vec<UsageProfile>>{if let Some(input)=cli_proxy{match cli_proxy_usage_limits(&input){Ok(profiles)=>return Ok(profiles),Err(proxy_error)=>return local_usage_limits().map_err(|local_error|format!("CLIProxyAPI 查询失败：{proxy_error}；本机回退也失败：{local_error}"))}}local_usage_limits()}
#[tauri::command] fn legacy_reset_usage_limit(scope:String,cli_proxy:Option<CliProxyInput>)->AppResult<String>{if scope.starts_with("cliproxy:"){return reset_proxy_usage(&cli_proxy.ok_or("请提供 CLIProxyAPI 连接信息。")?,&scope)}let(home,label)=profile_home(&scope)?;let limits=app_server_request(&home,"account/rateLimits/read",json!({"excludeResetCreditDetails":false,"supportsLunaReserve":false}))?;let credit=limits.get("rateLimitResetCredits").and_then(|v|v.get("credits")).and_then(Value::as_array).and_then(|credits|credits.iter().find(|credit|credit.get("status").and_then(Value::as_str)==Some("available"))).and_then(|credit|credit.get("id")).and_then(Value::as_str).ok_or("当前账号没有可用的额度重置次数。")?;let _=app_server_request(&home,"account/rateLimitResetCredit/consume",json!({"creditId":credit,"idempotencyKey":uuid::Uuid::new_v4().to_string()}))?;log_entry("USAGE RESET",&format!("已为“{}”提交一次额度重置。",label));Ok(format!("已为“{}”提交额度重置，正在刷新最新额度。",label))}
}
fn auth_token(value:&Value)->Option<String>{value.get("tokens").and_then(|tokens|tokens.get("access_token")).or_else(||value.get("access_token")).and_then(Value::as_str).filter(|token|!token.trim().is_empty()).map(str::to_owned)}
fn direct_usage_request(home:&Path,method:&str,path:&str,body:Option<Value>)->AppResult<Value>{let auth:Value=fs::read_to_string(home.join("auth.json")).map_err(|_|"无法读取本地 Codex 登录态。") .and_then(|text|serde_json::from_str(&text).map_err(|_|"本地 Codex 登录态格式无效。".into()))?;let token=auth_token(&auth).ok_or("本地登录态缺少访问令牌，请重新登录。")?;let account=auth_account_id(&auth).ok_or("本地登录态缺少账户标识，请重新登录。")?;let client=reqwest::blocking::Client::builder().timeout(Duration::from_secs(20)).build().map_err(|_|"创建额度连接失败。")?;let url=format!("https://chatgpt.com/backend-api/wham/{path}");let request=match method{"GET"=>client.get(&url),"POST"=>client.post(&url),_=>return Err("不支持的额度请求。".into())}.bearer_auth(token).header("Chatgpt-Account-Id",account).header("User-Agent","Codex Idea Tool");let response=match body{Some(body)=>request.json(&body).send(),None=>request.send()}.map_err(|_|"无法连接额度服务，请检查网络后重试。")?;let status=response.status();if !status.is_success(){return Err(format!("额度服务返回 HTTP {status}。"))}let response_text=response.text().map_err(|_|"无法读取额度服务响应。")?;if path=="usage"{log_entry("USAGE API RESPONSE",&format!("Endpoint={method} /backend-api/wham/{path}\nHTTP={status}\nBody={response_text}"));}serde_json::from_str::<Value>(&response_text).map_err(|_|"额度服务返回了无法解析的数据。".into())}
fn direct_usage_limits()->AppResult<Vec<UsageProfile>>{
 let accounts=load_accounts()?;
 let mut candidates=vec![];
 for account in accounts{
  let home=profiles_dir()?.join(&account.id);
  if home.join("auth.json").exists(){candidates.push((account.id,format!("OpenAI · {}",account.name),home))}
 }
 if let Some(home)=default_codex_home(){
  let auth=home.join("auth.json");
  if auth.exists(){
   let name=auth_display_name_at(&auth).unwrap_or_else(||"默认 Codex 登录态".into());
   candidates.push(("default".to_string(),format!("OpenAI · {name}"),home));
  }
 }
 let mut seen=HashSet::new();
 let mut profiles=vec![];
 for(scope,label,home)in candidates{
  let identity=auth_account_id_at(&home.join("auth.json")).unwrap_or_else(||scope.clone());
  if !seen.insert(identity){continue}
  match(direct_usage_request(&home,"GET","usage",None),direct_usage_request(&home,"GET","rate-limit-reset-credits",None)){
   (Ok(usage),Ok(credits))=>{
    let profile=usage_profile(scope,label.clone(),"direct",usage,Some(credits));
    log_entry("USAGE PARSED",&format!("Account={label}\nPrimary={}\nSecondary={}\nResetCredits={}",profile.primary.as_ref().map(|window|format!("remaining={}%, resets_at={:?}",window.remaining_percent,window.resets_at)).unwrap_or_else(||"null".into()),profile.secondary.as_ref().map(|window|format!("remaining={}%, resets_at={:?}",window.remaining_percent,window.resets_at)).unwrap_or_else(||"null".into()),profile.reset_credits));
    profiles.push(profile);
   },
   (Err(error),_)|(_,Err(error))=>{
    log_entry("USAGE ERROR",&format!("Account={label}\nError={error}"));
    profiles.push(usage_error(scope,label,"direct",error));
   }
  }
 }
 if profiles.is_empty(){Err("没有已登录的 Codex 账号可查询。".into())}else{Ok(profiles)}
}
#[tauri::command] async fn load_usage_limits()->AppResult<Vec<UsageProfile>>{tauri::async_runtime::spawn_blocking(direct_usage_limits).await.map_err(|error|format!("额度后台任务异常：{error}"))?}
#[tauri::command] async fn load_usage_limit(scope:String)->AppResult<UsageProfile>{tauri::async_runtime::spawn_blocking(move||direct_usage_limits()?.into_iter().find(|profile|profile.scope==scope).ok_or("未找到该账号的额度信息。".into())).await.map_err(|error|format!("额度后台任务异常：{error}"))?}
fn reset_usage_limit_blocking(scope:String)->AppResult<String>{let(home,label)=profile_home(&scope)?;let credits=direct_usage_request(&home,"GET","rate-limit-reset-credits",None)?;let credit=credits.get("credits").and_then(Value::as_array).and_then(|items|items.iter().find(|item|item.get("status").and_then(Value::as_str)==Some("available"))).and_then(|item|item.get("id")).and_then(Value::as_str).ok_or("当前账号没有可用的额度重置次数。")?;let _=direct_usage_request(&home,"POST","rate-limit-reset-credits/consume",Some(json!({"credit_id":credit,"redeem_request_id":uuid::Uuid::new_v4().to_string()})))?;log_entry("USAGE RESET",&format!("已为“{}”提交一次额度重置。",label));Ok(format!("已为“{}”提交额度重置，正在刷新最新额度。",label))}
#[tauri::command] async fn reset_usage_limit(scope:String)->AppResult<String>{tauri::async_runtime::spawn_blocking(move||reset_usage_limit_blocking(scope)).await.map_err(|error|format!("额度重置后台任务异常：{error}"))?}
fn load_providers()->AppResult<Vec<Provider>>{
 let store=providers_path()?;let saved:Vec<Provider>=read_json(&store);if !saved.is_empty()||store.exists(){return Ok(saved)}
 let cfg=config_path()?;let Ok(text)=fs::read_to_string(&cfg)else{return Ok(vec![])};
 let models:HashMap<String,String>=read_json(&config_dir()?.join("provider-models.json"));
 let catalogs:HashMap<String,Vec<String>>=read_json(&config_dir()?.join("provider-catalog-models.json"));
 let modes:HashMap<String,String>=read_json(&config_dir()?.join("provider-reasoning-modes.json"));
 let heading=Regex::new(r"(?m)^[ \t]*\[model_providers\.([A-Za-z0-9_-]+)\][ \t]*\r?$").map_err(|e|e.to_string())?;
 let value=|block:&str,key:&str|->String{Regex::new(&format!(r#"(?m)^\s*{}\s*=\s*\"([^\"]*)\""#,regex::escape(key))).ok().and_then(|r|r.captures(block)).and_then(|c|c.get(1)).map(|x|x.as_str().replace("\\\"","\"").replace("\\\\","\\")).unwrap_or_default()};
 let sections=heading.captures_iter(&text).filter_map(|c|Some((c.get(1)?.as_str().to_string(),c.get(0)?.end(),c.get(0)?.start()))).collect::<Vec<_>>();
 let mut items=vec![];for (index,(id,start,_)) in sections.iter().enumerate(){let end=sections.get(index+1).map(|x|x.2).unwrap_or(text.len());let block=&text[*start..end];let model=models.get(id).cloned().unwrap_or_else(||value(&text,"model"));let list=catalogs.get(id).cloned().unwrap_or_else(||if model.is_empty(){vec![]}else{vec![model.clone()]});let mut reasoning=HashMap::new();for m in &list{if let Some(raw)=modes.get(&format!("{}|{}",id,m)){let mut supported=vec![];let mut default_level="high".to_string();if raw.starts_with("levels="){for part in raw.split(';'){if let Some(x)=part.strip_prefix("levels="){supported=x.split(',').map(str::to_owned).collect()}if let Some(x)=part.strip_prefix("default="){default_level=x.to_string()}}}else{supported.push(raw.clone());default_level=raw.clone()}if supported.is_empty(){supported.push("high".into())}reasoning.insert(m.clone(),ReasoningConfig{levels:supported,default_level});}}
 items.push(Provider{id:id.clone(),name:value(block,"name").trim().to_string(),model,url:value(block,"base_url"),protocol:{let x=value(block,"wire_api");if x.is_empty(){"responses".into()}else{x}},models:list,reasoning_by_model:reasoning,api_key:value(block,"experimental_bearer_token")});}
 if !items.is_empty(){atomic_write(&store,&serde_json::to_string_pretty(&items).map_err(|e|e.to_string())?)?;log_entry("MIGRATION",&format!("已从旧版配置迁移 {} 个 Provider。",items.len()));}Ok(items)
}
fn save_providers(v:&[Provider])->AppResult<()>{let p=providers_path()?;backup(&p)?;atomic_write(&p,&serde_json::to_string_pretty(v).map_err(|e|e.to_string())?)}
fn load_accounts()->AppResult<Vec<Account>>{
 let path=accounts_path()?;
 if !path.exists(){return Ok(vec![])}
 let text=fs::read_to_string(&path).map_err(|e|format!("读取 OpenAI 账号索引失败（{}）：{e}",path.display()))?;
 let accounts:Vec<Account>=serde_json::from_str(&text).map_err(|e|format!("解析 OpenAI 账号索引失败（{}）：{e}",path.display()))?;
 // 旧版 .NET 使用 Id/Name；读取后立即规范化为新版格式，后续两版均可稳定识别。
 if text.contains("\"Id\"")||text.contains("\"Name\""){
  backup(&path)?;
  atomic_write(&path,&serde_json::to_string_pretty(&accounts).map_err(|e|e.to_string())?)?;
  log_entry("MIGRATION",&format!("已同步旧版 OpenAI 账号数据，共 {} 个账号。",accounts.len()));
 }
 Ok(accounts)
}
fn save_accounts(v:&[Account])->AppResult<()>{let p=accounts_path()?;backup(&p)?;atomic_write(&p,&serde_json::to_string_pretty(v).map_err(|e|e.to_string())?)}
fn default_reasoning()->ReasoningConfig{ReasoningConfig{levels:vec!["low".into(),"medium".into(),"high".into()],default_level:"high".into()}}

fn write_runtime(p:&Provider)->AppResult<()> {
 let cfg=config_path()?;backup(&cfg)?;let cat=catalog_path()?;
 let text=format!("model = \"{}\"\r\nmodel_provider = \"{}\"\r\nmodel_catalog_json = \"{}\"\r\n\r\n[model_providers.{}]\r\nname = \"{}\"\r\nbase_url = \"{}\"\r\nexperimental_bearer_token = \"{}\"\r\nwire_api = \"{}\"\r\n",escape(&p.model),p.id,escape(&cat.to_string_lossy()),p.id,escape(&p.name),escape(p.url.trim_end_matches('/')),escape(&p.api_key),escape(&p.protocol));atomic_write(&cfg,&text)?;
 let models=if p.models.is_empty(){vec![p.model.clone()]}else{p.models.clone()};
 let entries:Vec<Value>=models.iter().enumerate().map(|(i,m)|{let r=p.reasoning_by_model.get(m).cloned().unwrap_or_else(default_reasoning);let levels=if r.levels.is_empty(){default_reasoning().levels}else{r.levels};let def=if r.default_level=="auto"||!levels.contains(&r.default_level){if levels.iter().any(|x|x=="high"){"high".into()}else{levels[0].clone()}}else{r.default_level};json!({"slug":m,"display_name":format!("{} · {}",p.name,m),"description":format!("{} model: {}",p.name,m),"base_instructions":"You are Codex, a coding agent. You and the user share the same workspace and collaborate to achieve the user's goals.","default_reasoning_level":def,"supported_reasoning_levels":levels.iter().map(|x|json!({"effort":x,"description":format!("思考等级：{}",x)})).collect::<Vec<_>>(),"shell_type":"shell_command","visibility":"list","supported_in_api":true,"priority":i,"supports_reasoning_summaries":true,"default_reasoning_summary":"none","support_verbosity":false,"truncation_policy":{"mode":"bytes","limit":10000},"supports_parallel_tool_calls":false,"supports_image_detail_original":false,"context_window":262144,"max_context_window":262144,"effective_context_window_percent":95,"experimental_supported_tools":[],"input_modalities":["text","image"],"supports_search_tool":false})}).collect();
 atomic_write(&cat,&serde_json::to_string_pretty(&json!({"models":entries})).map_err(|e|e.to_string())?)?;log_entry("RUNTIME CONFIG",&format!("Provider={}\nModel={}\nBaseUrl={}\nProtocol={}\nConfig={}\nCatalog={}\nModelsVisibleToIdea={}",p.id,p.model,p.url,p.protocol,cfg.display(),cat.display(),models.join(", ")));Ok(())
}
fn recent_logs()->Vec<String>{let Ok(dir)=logs_dir()else{return vec![]};let mut f=fs::read_dir(dir).ok().into_iter().flatten().filter_map(|x|x.ok()).map(|x|x.path()).filter(|p|p.extension().and_then(|x|x.to_str())==Some("log")).collect::<Vec<_>>();f.sort();f.reverse();let all=f.into_iter().take(2).filter_map(|p|fs::read_to_string(p).ok()).collect::<Vec<_>>().join("");let lines=all.lines().collect::<Vec<_>>();let skip=lines.len().saturating_sub(180);lines.into_iter().skip(skip).map(str::to_owned).collect()}

#[tauri::command] fn load_app_data()->AppResult<AppData>{let ps=load_providers()?;let accounts=load_accounts()?;let runtime_status=runtime_status(&accounts);Ok(AppData{providers:ps.iter().map(ProviderView::from).collect(),accounts:accounts.into_iter().map(|a|{let logged=profiles_dir().map(|p|p.join(&a.id).join("auth.json").exists()).unwrap_or(false);AccountView{id:a.id,name:a.name,logged_in:logged}}).collect(),runtime_status,recent_logs:recent_logs(),config_dir:config_dir()?.to_string_lossy().into(),profiles_dir:profiles_dir()?.to_string_lossy().into(),logs_dir:logs_dir()?.to_string_lossy().into()})}

#[tauri::command] fn save_provider(input:SaveProviderInput)->AppResult<ProviderView>{let valid=Regex::new(r"^[A-Za-z0-9_-]+$").unwrap();if !valid.is_match(input.id.trim()){return Err("Provider ID 只能包含字母、数字、下划线和连字符。".into())}if input.model.trim().is_empty(){return Err("模型 ID 不能为空。".into())}if !(input.url.starts_with("http://")||input.url.starts_with("https://")){return Err("Base URL 必须是有效的 http/https 地址。".into())}let mut all=load_providers()?;let original=input.original_id.as_deref().map(str::trim).filter(|x|!x.is_empty());let old_index=original.and_then(|id|all.iter().position(|p|p.id.eq_ignore_ascii_case(id)));if let Some(from)=original{if !from.eq_ignore_ascii_case(input.id.trim())&&all.iter().any(|p|p.id.eq_ignore_ascii_case(input.id.trim())&&!p.id.eq_ignore_ascii_case(from)){return Err("Provider ID 已存在，请使用其他 ID。".into())}}else if all.iter().any(|p|p.id.eq_ignore_ascii_case(input.id.trim())){return Err("Provider ID 已存在。若要修改，请先在左侧选择该 Provider；新建时请使用其他 ID。".into())}let old=old_index.and_then(|i|all.get(i)).cloned();let key=input.api_key.filter(|x|!x.trim().is_empty()).or_else(||old.map(|x|x.api_key)).ok_or("API Key 不能为空。请输入新的 API Key，或先选择已有 Provider 再修改。")?;let mut models=input.models;if !models.iter().any(|x|x.eq_ignore_ascii_case(&input.model)){models.push(input.model.clone())}models.sort();models.dedup();let p=Provider{id:input.id.trim().into(),name:if input.name.trim().is_empty(){input.id.trim().into()}else{input.name.trim().into()},model:input.model.trim().into(),url:input.url.trim().trim_end_matches('/').into(),protocol:input.protocol,models,reasoning_by_model:input.reasoning_by_model,api_key:key};if let Some(i)=old_index{all[i]=p.clone()}else{all.push(p.clone())}save_providers(&all)?;write_runtime(&p)?;log_entry("SUCCESS",&format!("已保存 Provider：{} · {}",p.id,p.model));Ok(ProviderView::from(&p))}
#[tauri::command] fn delete_provider(id:String)->AppResult<()> {let mut all=load_providers()?;let before=all.len();all.retain(|x|!x.id.eq_ignore_ascii_case(&id));if before==all.len(){return Err("Provider 不存在。".into())}save_providers(&all)?;log_entry("SUCCESS",&format!("已删除 Provider：{id}"));Ok(())}

fn request_models(p:&Provider)->AppResult<Vec<String>>{let url=format!("{}/models",p.url.trim_end_matches('/'));log_entry("HTTP REQUEST",&format!("Method=GET\nUrl={url}\nProvider={}\nAuthorization=Bearer [REDACTED]",p.id));let client=reqwest::blocking::Client::builder().timeout(Duration::from_secs(25)).build().map_err(|e|e.to_string())?;let resp=client.get(&url).bearer_auth(&p.api_key).send().map_err(|e|format!("请求失败：{e}"))?;let status=resp.status();let headers=format!("{:?}",resp.headers());let body=resp.text().map_err(|e|e.to_string())?;log_entry("HTTP RESPONSE",&format!("Url={url}\nStatus={}\nHeaders={}\nBody={}",status,headers,body));if !status.is_success(){return Err(format!("获取模型失败：HTTP {}。完整响应已写入日志。",status))}let v:Value=serde_json::from_str(&body).map_err(|e|format!("返回内容不是有效 JSON：{e}"))?;let arr=v.get("data").or_else(||v.get("models")).and_then(Value::as_array).ok_or("响应成功，但没有识别到模型数组。")?;let mut ids=arr.iter().filter_map(|x|x.get("id").or_else(||x.get("name")).and_then(Value::as_str)).map(str::to_owned).collect::<Vec<_>>();ids.sort();ids.dedup();if ids.is_empty(){Err("接口响应成功，但没有识别到模型 ID。".into())}else{Ok(ids)}}
#[tauri::command] fn fetch_models(id:String,api_key:Option<String>,url:Option<String>)->AppResult<Vec<String>>{let mut all=load_providers()?;let saved_index=all.iter().position(|x|x.id.eq_ignore_ascii_case(&id));let mut p=saved_index.and_then(|i|all.get(i)).cloned().unwrap_or_else(||Provider{id:id.trim().into(),name:id.trim().into(),model:String::new(),url:String::new(),protocol:"responses".into(),models:vec![],reasoning_by_model:HashMap::new(),api_key:String::new()});if let Some(k)=api_key.filter(|x|!x.trim().is_empty()){p.api_key=k}if let Some(u)=url.filter(|x|!x.trim().is_empty()){p.url=u.trim().trim_end_matches('/').into()}if p.api_key.is_empty(){return Err("获取模型前请填写 API Key。".into())}if !(p.url.starts_with("http://")||p.url.starts_with("https://")){return Err("获取模型前请填写有效的 Base URL。".into())}let ids=request_models(&p)?;if let Some(i)=saved_index{all[i].models=ids.clone();save_providers(&all)?;}log_entry("SUCCESS",&format!("获取到 {} 个模型。",ids.len()));Ok(ids)}
#[tauri::command] fn test_provider(id:String,api_key:Option<String>,url:Option<String>)->AppResult<String>{let ids=fetch_models(id,api_key,url)?;Ok(format!("连接成功，共识别到 {} 个模型。",ids.len()))}

#[tauri::command] fn add_account(name:String)->AppResult<AccountView>{let n=name.trim();if n.is_empty(){return Err("账号名称不能为空。".into())}let mut all=load_accounts()?;if all.iter().any(|x|x.name.eq_ignore_ascii_case(n)){return Err("账号名称已存在。".into())}let a=Account{id:uuid::Uuid::new_v4().simple().to_string(),name:n.into()};all.push(a.clone());save_accounts(&all)?;fs::create_dir_all(profiles_dir()?.join(&a.id)).map_err(|e|e.to_string())?;Ok(AccountView{id:a.id,name:a.name,logged_in:false})}
fn find_codex()->Option<PathBuf>{if let Some(path)=std::env::var_os("PATH"){for d in std::env::split_paths(&path){let p=d.join("codex.exe");if p.exists(){return Some(p)}}}walk_find(&local_data().ok()?.join("OpenAI").join("Codex").join("bin"),"codex.exe")}
fn walk_find(dir:&Path,name:&str)->Option<PathBuf>{for e in fs::read_dir(dir).ok()?.flatten(){let p=e.path();if p.is_file()&&p.file_name()?.to_string_lossy().eq_ignore_ascii_case(name){return Some(p)}if p.is_dir(){if let Some(v)=walk_find(&p,name){return Some(v)}}}None}
#[tauri::command] fn login_account(id:String)->AppResult<String>{let a=load_accounts()?.into_iter().find(|x|x.id==id).ok_or("账号不存在。")?;let codex=find_codex().ok_or("未找到 codex.exe，请确认 Codex CLI 或桌面客户端已安装。")?;let home=profiles_dir()?.join(&a.id);fs::create_dir_all(&home).map_err(|e|e.to_string())?;atomic_write(&home.join("config.toml"),"cli_auth_credentials_store = \"file\"\r\n")?;Command::new(&codex).arg("login").env("CODEX_HOME",&home).spawn().map_err(|e|format!("启动登录失败：{e}"))?;log_entry("OPENAI LOGIN",&format!("Account={}\nCODEX_HOME={}\nMode=普通 OAuth",a.name,home.display()));Ok(format!("已启动“{}”普通 OAuth 登录；完成浏览器授权后状态会自动刷新。",a.name))}
fn normalize_auth(v:Value)->AppResult<Value>{if !v.is_object(){return Err("认证文件根节点必须是 JSON 对象。".into())}if v.get("auth_mode").is_some(){if v.get("auth_mode").and_then(Value::as_str)==Some("chatgpt")&&v.get("tokens").and_then(Value::as_object).is_none(){return Err("ChatGPT 认证缺少 tokens 对象。".into())}return Ok(v)}let access=v.get("access_token").and_then(Value::as_str).ok_or("缺少 access_token")?.to_owned();let idt=v.get("id_token").and_then(Value::as_str).ok_or("缺少 id_token")?.to_owned();let refresh=v.get("refresh_token").and_then(Value::as_str).ok_or("缺少 refresh_token")?.to_owned();let account=v.get("account_id").and_then(Value::as_str).ok_or("缺少 account_id")?.to_owned();Ok(json!({"auth_mode":"chatgpt","OPENAI_API_KEY":null,"tokens":{"id_token":idt,"access_token":access,"refresh_token":refresh,"account_id":account},"last_refresh":Local::now().to_rfc3339()}))}
#[tauri::command] fn import_account_auth(id:String)->AppResult<String>{let a=load_accounts()?.into_iter().find(|x|x.id==id).ok_or("账号不存在。")?;let source=rfd::FileDialog::new().add_filter("Codex 认证文件",&["json"]).set_file_name("auth.json").pick_file().ok_or("已取消导入。")?;let v:Value=serde_json::from_str(&fs::read_to_string(&source).map_err(|e|format!("读取认证文件失败：{e}"))?).map_err(|e|format!("认证 JSON 格式错误：{e}"))?;let normalized=normalize_auth(v)?;let home=profiles_dir()?.join(&a.id);fs::create_dir_all(&home).map_err(|e|e.to_string())?;let target=home.join("auth.json");backup(&target)?;atomic_write(&home.join("config.toml"),"cli_auth_credentials_store = \"file\"\r\n")?;atomic_write(&target,&serde_json::to_string_pretty(&normalized).map_err(|e|e.to_string())?)?;log_entry("SUCCESS",&format!("已为账号“{}”导入认证：{}",a.name,source.display()));Ok("认证导入成功。".into())}
#[tauri::command] fn delete_account(id:String)->AppResult<()> {let mut all=load_accounts()?;let a=all.iter().find(|x|x.id==id).cloned().ok_or("账号不存在。")?;all.retain(|x|x.id!=id);save_accounts(&all)?;let home=profiles_dir()?.join(&a.id);if home.exists(){fs::remove_dir_all(&home).map_err(|e|e.to_string())?}log_entry("SUCCESS",&format!("已删除 OpenAI 账号：{}",a.name));Ok(())}

fn idea_path()->AppResult<PathBuf>{let saved=config_dir()?.join("idea-path.txt");if let Ok(s)=fs::read_to_string(&saved){let p=PathBuf::from(s.trim());if p.exists(){return Ok(p)}}let picked=rfd::FileDialog::new().add_filter("IntelliJ IDEA",&["exe"]).set_file_name("idea64.exe").pick_file().ok_or("已取消选择 IDEA。")?;atomic_write(&saved,&picked.to_string_lossy())?;Ok(picked)}
fn configure_idea_acp(){let Some(appdata)=std::env::var_os("APPDATA")else{return};let root=PathBuf::from(appdata).join("JetBrains");let Ok(dirs)=fs::read_dir(root)else{return};let mut files=dirs.flatten().map(|x|x.path().join("options").join("acpAgents.xml")).filter(|p|p.exists()).collect::<Vec<_>>();files.sort_by_key(|p|fs::metadata(p).and_then(|m|m.modified()).ok());let Some(path)=files.pop()else{return};let Ok(mut text)=fs::read_to_string(&path)else{return};let original=text.clone();if let Ok(re)=Regex::new(r#"(<entry\s+key=\"acp\.registry\.codex-acp\"\s+value=\")[^\"]*(\"\s*/>)"#){text=re.replace(&text,"${1}MANAGED_EXTERNALLY${2}").into_owned()}if text!=original{let _=backup(&path);let _=atomic_write(&path,&text);}}
fn idea_process_ids()->Vec<u32>{unsafe{let snapshot=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if snapshot==INVALID_HANDLE_VALUE{return vec![]}let mut entry:PROCESSENTRY32W=std::mem::zeroed();entry.dwSize=std::mem::size_of::<PROCESSENTRY32W>() as u32;let mut ids=vec![];if Process32FirstW(snapshot,&mut entry)!=0{loop{let end=entry.szExeFile.iter().position(|&c|c==0).unwrap_or(entry.szExeFile.len());if String::from_utf16_lossy(&entry.szExeFile[..end]).eq_ignore_ascii_case("idea64.exe"){ids.push(entry.th32ProcessID)}if Process32NextW(snapshot,&mut entry)==0{break}}}CloseHandle(snapshot);ids}}
fn runtime_status(accounts:&[Account])->RuntimeStatus{let pids=idea_process_ids();if pids.is_empty(){return RuntimeStatus{state:"stopped".into(),label:"未检测到运行中的 IDEA".into(),detail:"启动 IDEA 后会在这里显示正在使用的配置。".into()}}if let Ok(path)=launch_record_path(){if let Some(record)=fs::read_to_string(path).ok().and_then(|text|serde_json::from_str::<LaunchRecord>(&text).ok()){if pids.contains(&record.pid){return RuntimeStatus{state:"managed".into(),label:record.label,detail:"由 Codex Idea Tool 启动，配置已确认。".into()}}}}let default_auth=default_codex_home().map(|home|home.join("auth.json"));if let Some(account_id)=default_auth.as_deref().and_then(auth_account_id_at){if let Some(account)=accounts.iter().find(|account|profiles_dir().ok().map(|root|root.join(&account.id).join("auth.json")).as_deref().and_then(auth_account_id_at).as_deref()==Some(account_id.as_str())){return RuntimeStatus{state:"default".into(),label:format!("OpenAI · {}",account.name),detail:"普通方式启动的 IDEA，已与默认 Codex 登录态匹配。".into()}}return RuntimeStatus{state:"default".into(),label:"OpenAI · 默认 Codex 登录态".into(),detail:"普通方式启动的 IDEA；该登录态尚未与本工具中的账号名称匹配。".into()}}RuntimeStatus{state:"unverified".into(),label:"无法确认当前账号".into(),detail:"IDEA 正在运行，但未发现可识别的默认 Codex 登录态；可能由自定义脚本或环境启动。".into()}}
#[tauri::command] fn launch_idea(kind:String,id:String)->AppResult<String>{let started=Instant::now();if !idea_process_ids().is_empty(){return Err("检测到 IDEA 仍在运行。请完全退出所有 IDEA 窗口和后台进程后再启动。".into())}let check_ms=started.elapsed().as_millis();let idea=idea_path()?;let path_ms=started.elapsed().as_millis();configure_idea_acp();let acp_ms=started.elapsed().as_millis();let (home,label,extra)=if kind=="provider"{let p=load_providers()?.into_iter().find(|x|x.id==id).ok_or("Provider 不存在。")?;write_runtime(&p)?;let cfg=json!({"model":p.model,"model_provider":p.id,"model_catalog_json":catalog_path()?.to_string_lossy(),"model_providers":{p.id.clone():{"name":p.name,"base_url":p.url,"experimental_bearer_token":p.api_key,"wire_api":p.protocol}}});(config_dir()?,format!("第三方 · {}",p.id),Some((p.id,serde_json::to_string(&cfg).map_err(|e|e.to_string())?)))}else{let a=load_accounts()?.into_iter().find(|x|x.id==id).ok_or("OpenAI 账号不存在。")?;let h=profiles_dir()?.join(&a.id);if !h.join("auth.json").exists(){return Err("该 OpenAI 账号尚未登录或导入认证。".into())}(h,format!("OpenAI · {}",a.name),None)};let config_ms=started.elapsed().as_millis();let mut cmd=Command::new(&idea);cmd.env("CODEX_HOME",&home).env_remove("CODEX_CONFIG").env_remove("MODEL_PROVIDER");if let Some((provider,cfg))=extra{cmd.env("MODEL_PROVIDER",provider).env("CODEX_CONFIG",cfg);}let child=cmd.spawn().map_err(|e|format!("启动 IDEA 失败：{e}"))?;atomic_write(&launch_record_path()?,&serde_json::to_string(&LaunchRecord{pid:child.id(),label:label.clone()}).map_err(|e|e.to_string())?)?;let total_ms=started.elapsed().as_millis();log_entry("IDEA LAUNCH CONFIG",&format!("IDEA={}\nProfile={}\nCODEX_HOME={}\nConfigExists={}\nAuthExists={}\nTimingMs=process-check:{}, idea-path:{}, acp-config:{}, runtime-config:{}, total:{}",idea.display(),label,home.display(),home.join("config.toml").exists(),home.join("auth.json").exists(),check_ms,path_ms.saturating_sub(check_ms),acp_ms.saturating_sub(path_ms),config_ms.saturating_sub(acp_ms),total_ms));Ok(format!("已使用“{}”启动隔离 IDEA（准备耗时 {} ms）。",label,total_ms))}

#[tauri::command] fn open_app_dir(kind:String)->AppResult<()> {let p=match kind.as_str(){"logs"=>logs_dir()?,"profiles"=>profiles_dir()?,_=>config_dir()?};fs::create_dir_all(&p).map_err(|e|e.to_string())?;Command::new("explorer.exe").arg(p).spawn().map_err(|e|e.to_string())?;Ok(())}
#[tauri::command] fn restore_latest_backup()->AppResult<String>{let dir=config_dir()?;let target=config_path()?;let mut b=fs::read_dir(&dir).map_err(|e|e.to_string())?.flatten().map(|x|x.path()).filter(|p|p.file_name().is_some_and(|n|n.to_string_lossy().starts_with("config.toml.backup-"))).collect::<Vec<_>>();b.sort();let latest=b.pop().ok_or("没有可恢复的配置备份。")?;backup(&target)?;fs::copy(&latest,&target).map_err(|e|e.to_string())?;log_entry("SUCCESS",&format!("已恢复备份：{}",latest.display()));Ok(format!("已恢复最近备份：{}",latest.file_name().unwrap_or_default().to_string_lossy()))}
#[tauri::command] fn clean_backups()->AppResult<String>{let roots=[config_dir()?,profiles_dir()?];let mut groups:HashMap<String,Vec<PathBuf>>=HashMap::new();for root in roots{collect_backups(&root,&mut groups)}let mut removed=0;for files in groups.values_mut(){files.sort();let count=files.len().saturating_sub(5);for p in files.iter().take(count){fs::remove_file(p).map_err(|e|e.to_string())?;removed+=1}}log_entry("SUCCESS",&format!("已清理 {removed} 份历史备份，每组保留最近 5 份。"));Ok(format!("已清理 {removed} 份历史备份；每组最多保留 5 份。"))}
fn collect_backups(root:&Path,groups:&mut HashMap<String,Vec<PathBuf>>){let Ok(entries)=fs::read_dir(root)else{return};for e in entries.flatten(){let p=e.path();if p.is_dir(){collect_backups(&p,groups)}else if let Some(n)=p.file_name().and_then(|x|x.to_str()){if let Some((base,_))=n.split_once(".backup-"){groups.entry(format!("{}\\{}",p.parent().unwrap_or(root).display(),base)).or_default().push(p)}}}}

#[cfg(test)]
mod tests {
 use super::*;
 #[test] fn legacy_account_fields_are_supported(){let accounts:Vec<Account>=serde_json::from_str(r#"[{"Id":"legacy-id","Name":"旧账号"}]"#).expect("legacy account json should parse");assert_eq!(accounts.len(),1);assert_eq!(accounts[0].id,"legacy-id");assert_eq!(accounts[0].name,"旧账号");}
 #[test] fn auth_account_id_supports_current_and_legacy_formats(){let current:Value=serde_json::from_str(r#"{"auth_mode":"chatgpt","tokens":{"account_id":"current-account"}}"#).unwrap();let legacy:Value=serde_json::from_str(r#"{"account_id":"legacy-account"}"#).unwrap();assert_eq!(auth_account_id(&current).as_deref(),Some("current-account"));assert_eq!(auth_account_id(&legacy).as_deref(),Some("legacy-account"));}
 #[test] fn usage_profile_exposes_remaining_windows_and_credit_count(){let result:Value=serde_json::from_str(r#"{"rateLimits":{"planType":"plus","primary":{"usedPercent":25,"resetsAt":100},"secondary":{"usedPercent":80,"resetsAt":200}},"rateLimitResetCredits":{"availableCount":2}}"#).unwrap();let profile=usage_profile("default".into(),"默认".into(),"local",result,None);assert_eq!(profile.primary.unwrap().remaining_percent,75.0);assert_eq!(profile.secondary.unwrap().remaining_percent,20.0);assert_eq!(profile.reset_credits,2);assert_eq!(profile.plan_type.as_deref(),Some("plus"));}
 #[test] fn direct_usage_profile_parses_snake_case_windows_and_credits(){let usage:Value=serde_json::from_str(r#"{"rate_limit":{"plan_type":"pro","primary_window":{"used_percent":40,"reset_at":100},"secondary_window":{"used_percent":90,"reset_at":200}}}"#).unwrap();let credits:Value=serde_json::from_str(r#"{"credits":[{"id":"a","status":"available"},{"id":"b","status":"used"}]}"#).unwrap();let profile=usage_profile("default".into(),"work".into(),"direct",usage,Some(credits));assert_eq!(profile.primary.unwrap().remaining_percent,60.0);assert_eq!(profile.secondary.unwrap().remaining_percent,10.0);assert_eq!(profile.reset_credits,1);assert_eq!(profile.plan_type.as_deref(),Some("pro"));}
 #[test] fn single_week_window_is_exposed_as_secondary(){let usage:Value=serde_json::from_str(r#"{"rate_limit":{"primary_window":{"used_percent":100,"limit_window_seconds":604800,"reset_at":200}}}"#).unwrap();let profile=usage_profile("default".into(),"work".into(),"direct",usage,None);assert!(profile.primary.is_none());assert_eq!(profile.secondary.unwrap().remaining_percent,0.0);}
 #[test] fn window_duration_wins_when_api_field_order_is_reversed(){let usage:Value=serde_json::from_str(r#"{"rate_limit":{"primary_window":{"used_percent":80,"limit_window_seconds":604800,"reset_at":200},"secondary_window":{"used_percent":25,"limit_window_seconds":18000,"reset_at":100}}}"#).unwrap();let profile=usage_profile("default".into(),"work".into(),"direct",usage,None);assert_eq!(profile.primary.unwrap().remaining_percent,75.0);assert_eq!(profile.secondary.unwrap().remaining_percent,20.0);}
 #[test] fn auth_token_supports_current_and_legacy_formats(){let current:Value=serde_json::from_str(r#"{"tokens":{"access_token":"current-token"}}"#).unwrap();let legacy:Value=serde_json::from_str(r#"{"access_token":"legacy-token"}"#).unwrap();assert_eq!(auth_token(&current).as_deref(),Some("current-token"));assert_eq!(auth_token(&legacy).as_deref(),Some("legacy-token"));}
 #[test] fn provider_store_load_is_safe_without_machine_data(){let _=load_providers().expect("provider loading should not fail when machine data is absent");}
 #[test] fn log_redaction_hides_bearer(){assert!(!redact("Authorization: Bearer secret-value").contains("secret-value"));}
}

#[cfg_attr(mobile, tauri::mobile_entry_point)] pub fn run(){tauri::Builder::default().plugin(tauri_plugin_single_instance::init(|app,_,_|{if let Some(w)=app.get_webview_window("main"){let _=w.show();let _=w.set_focus();}})).setup(|app|{if cfg!(debug_assertions){app.handle().plugin(tauri_plugin_log::Builder::default().level(log::LevelFilter::Info).build())?;}Ok(())}).invoke_handler(tauri::generate_handler![load_app_data,load_usage_limits,load_usage_limit,reset_usage_limit,save_provider,delete_provider,fetch_models,test_provider,add_account,login_account,import_account_auth,delete_account,launch_idea,open_app_dir,restore_latest_backup,clean_backups]).run(tauri::generate_context!()).expect("error while running tauri application");}
