import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { CircleHelp, Download, FileCog, FolderOpen, KeyRound, Play, Plus, RefreshCw, RotateCcw, Save, Settings2, Trash2, UserRound, X } from 'lucide-react'
import './App.css'

type Page='launch'|'providers'|'accounts'; type Reasoning={levels:string[];defaultLevel:string}
type Provider={id:string;name:string;model:string;url:string;protocol:string;models:string[];reasoningByModel:Record<string,Reasoning>;hasApiKey:boolean}
type Account={id:string;name:string;loggedIn:boolean}; type AppData={providers:Provider[];accounts:Account[];recentLogs:string[]}
const blank=():Provider=>({id:'',name:'',model:'',url:'',protocol:'responses',models:[],reasoningByModel:{},hasApiKey:false})
const levels=[['none','无'],['minimal','极简'],['low','低'],['medium','中'],['high','高'],['xhigh','超高'],['max','最大'],['ultra','极致']]
const message=(e:unknown)=>typeof e==='string'?e:e instanceof Error?e.message:String(e)
const levelName=(id:string)=>levels.find(x=>x[0]===id)?.[1]||id

export default function App(){
 const[page,setPage]=useState<Page>('launch'),[providers,setProviders]=useState<Provider[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[source,setSource]=useState(''),[logs,setLogs]=useState<string[]>(['正在读取本地配置…']),[help,setHelp]=useState(false),[busy,setBusy]=useState('')
 const refresh=useCallback(async(silent=false)=>{try{const d=await invoke<AppData>('load_app_data');setProviders(d.providers);setAccounts(d.accounts);if(!silent)setLogs(d.recentLogs.length?d.recentLogs:['Codex Provider Manager 已就绪']);setSource(v=>v&&([...d.providers.map(x=>'provider:'+x.id),...d.accounts.map(x=>'account:'+x.id)]).includes(v)?v:(d.providers[0]?'provider:'+d.providers[0].id:d.accounts[0]?'account:'+d.accounts[0].id:''))}catch(e){setLogs(x=>[...x,'[ERROR] '+message(e)])}},[])
 useEffect(()=>{refresh();const timer=setInterval(()=>refresh(true),2500);return()=>clearInterval(timer)},[refresh])
 const run=async(label:string,task:()=>Promise<unknown>)=>{setBusy(label);try{const result=await task();setLogs(x=>[...x,`[SUCCESS] ${typeof result==='string'?result:label+'完成'}`]);await refresh(true)}catch(e){setLogs(x=>[...x,'[ERROR] '+message(e)])}finally{setBusy('')}}
 const launch=()=>{if(!source)return setLogs(x=>[...x,'[ERROR] 请先创建一个 Provider 或 OpenAI 账号。']);const[kind,id]=source.split(':');run('启动 IDEA',()=>invoke('launch_idea',{kind,id}))}
 return <div className="app-shell"><nav className="tabs">{([['launch','启动配置',Play],['providers','第三方 Provider',Settings2],['accounts','OpenAI 账号',UserRound]] as const).map(([id,label,Icon])=><button className={page===id?'tab active':'tab'} key={id} onClick={()=>setPage(id)}><Icon size={16}/>{label}</button>)}<button className="icon-button tab-help" title="配置说明" aria-label="配置说明" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button></nav><main className="content">{page==='launch'&&<Launch providers={providers} accounts={accounts} source={source} setSource={setSource} launch={launch} busy={busy}/>} {page==='providers'&&<Providers providers={providers} refresh={refresh} run={run} busy={busy}/>} {page==='accounts'&&<Accounts accounts={accounts} run={run} busy={busy}/>}</main><Logs logs={logs} clear={()=>setLogs([])} run={run}/>{help&&<Help close={()=>setHelp(false)}/>}</div>
}
function Title({icon,title,desc}:{icon:ReactNode;title:string;desc:string}){return <div className="panel-title"><span className="title-icon">{icon}</span><div><h1>{title}</h1><p>{desc}</p></div></div>}
function Launch({providers,accounts,source,setSource,launch,busy}:{providers:Provider[];accounts:Account[];source:string;setSource:(x:string)=>void;launch:()=>void;busy:string}){return <section className="panel launch-panel"><Title icon={<Play size={19}/>} title="选择要启动的配置" desc="第三方 Provider 和 OpenAI 账号彼此隔离，不影响 Codex 桌面客户端。"/><label className="source-label"><span>配置来源</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="">请选择配置</option>{providers.length>0&&<optgroup label="第三方 Provider">{providers.map(p=><option key={p.id} value={'provider:'+p.id}>{p.name} · {p.model}</option>)}</optgroup>}{accounts.length>0&&<optgroup label="OpenAI 账号">{accounts.map(a=><option key={a.id} value={'account:'+a.id}>OpenAI · {a.name}{a.loggedIn?' · 已登录':' · 未登录'}</option>)}</optgroup>}</select></label><button className="primary large" disabled={!!busy||!source} onClick={launch}><Play size={17}/>{busy==='启动 IDEA'?'正在启动…':'启动隔离 IDEA'}</button><div className="notice">请先完全退出所有 IDEA。直接从普通快捷方式启动 IDEA 时，仍使用系统默认 Codex 配置。</div></section>}

function Providers({providers,refresh,run,busy}:{providers:Provider[];refresh:(s?:boolean)=>Promise<void>;run:(l:string,t:()=>Promise<unknown>)=>Promise<void>;busy:string}){
 const[selected,setSelected]=useState(''),[draft,setDraft]=useState<Provider>(blank()),[key,setKey]=useState(''),[reasonOpen,setReasonOpen]=useState(false)
 useEffect(()=>{const p=providers.find(x=>x.id===selected)||providers[0];if(p){setSelected(p.id);setDraft(structuredClone(p));setKey('')}else{setSelected('');setDraft(blank())}},[providers,selected])
 const pick=(id:string)=>{const p=providers.find(x=>x.id===id);if(p){setSelected(id);setDraft(structuredClone(p));setKey('')}};const update=(k:keyof Provider,v:string)=>setDraft(d=>({...d,[k]:v}))
 const save=()=>run('保存配置',async()=>{await invoke('save_provider',{input:{id:draft.id,name:draft.name,model:draft.model,url:draft.url,protocol:draft.protocol,apiKey:key||null,models:draft.models,reasoningByModel:draft.reasoningByModel}});await refresh(true);return `已保存 Provider：${draft.name||draft.id}`})
 const fetch=()=>run('获取模型',async()=>{const ids=await invoke<string[]>('fetch_models',{id:draft.id,apiKey:key||null,url:draft.url});setDraft(d=>({...d,models:ids,model:ids.includes(d.model)?d.model:ids[0]}));await refresh(true);return `已获取 ${ids.length} 个模型，列表已保存。`})
 const del=()=>{if(confirm(`确定删除 Provider“${draft.name||draft.id}”吗？`))run('删除 Provider',()=>invoke('delete_provider',{id:draft.id}))}
 const currentReason=draft.reasoningByModel[draft.model]||{levels:['low','medium','high'],defaultLevel:'high'}
 return <section className="panel provider-panel"><Title icon={<Settings2 size={19}/>} title="第三方 Provider" desc="配置兼容 OpenAI API 的模型服务，并为每个模型独立设置推理程度。"/><div className="provider-layout"><aside className="provider-list">{providers.map(p=><button className={p.id===selected?'provider-item selected':'provider-item'} key={p.id} onClick={()=>pick(p.id)}><b>{p.name||p.id}</b><small>{p.model||'未填写模型'}</small></button>)}<button className="outline add-provider" onClick={()=>{setSelected('');setDraft(blank());setKey('')}}><Plus size={15}/>新建 Provider</button></aside><div className="form-grid"><Field label="Provider ID"><input value={draft.id} onChange={e=>update('id',e.target.value)}/></Field><Field label="显示名称"><input value={draft.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="模型 ID"><input list="model-list" value={draft.model} onChange={e=>update('model',e.target.value)}/><datalist id="model-list">{draft.models.map(x=><option key={x} value={x}/>)}</datalist></Field><Field label="Base URL"><input placeholder="https://api.example.com/v1" value={draft.url} onChange={e=>update('url',e.target.value)}/></Field><Field label="API Key"><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder={draft.hasApiKey?'已保存；留空则保留原密钥':'请输入 API Key'}/></Field><Field label="协议"><select value={draft.protocol} onChange={e=>update('protocol',e.target.value)}><option value="responses">Responses API</option><option value="chat">Chat Completions</option></select></Field><div className="reason-summary"><div><span>当前模型推理程度</span><b>{draft.model||'尚未选择模型'}</b><small>支持：{currentReason.levels.map(levelName).join('、')}　默认：{currentReason.defaultLevel==='auto'?'自动':levelName(currentReason.defaultLevel)}</small></div><button className="outline" onClick={()=>setReasonOpen(true)}><Settings2 size={16}/>配置全部模型</button></div><div className="actions"><button className="primary" disabled={!!busy} onClick={save}><Save size={16}/>保存配置</button><button className="outline" disabled={!!busy} onClick={fetch}><RefreshCw size={16}/>获取模型</button><button className="outline" disabled={!!busy} onClick={()=>run('测试连接',()=>invoke('test_provider',{id:draft.id,apiKey:key||null,url:draft.url}))}><KeyRound size={16}/>测试连接</button><button className="outline" onClick={()=>run('恢复备份',()=>invoke('restore_latest_backup'))}><RotateCcw size={16}/>恢复备份</button><button className="outline" onClick={()=>run('清理备份',()=>invoke('clean_backups'))}><Trash2 size={16}/>清理备份</button><button className="danger" disabled={!selected} onClick={del}><Trash2 size={16}/>删除当前</button></div></div></div>{reasonOpen&&<ReasonModal provider={draft} update={setDraft} close={()=>setReasonOpen(false)}/>}</section>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span><div className="field-control">{children}</div></label>}
function ReasonModal({provider,update,close}:{provider:Provider;update:(p:Provider)=>void;close:()=>void}){const models=useMemo(()=>Array.from(new Set([provider.model,...provider.models].filter(Boolean))),[provider]);const[current,setCurrent]=useState(models[0]||'');const value=provider.reasoningByModel[current]||{levels:['low','medium','high'],defaultLevel:'high'};const set=(v:Reasoning)=>update({...provider,reasoningByModel:{...provider.reasoningByModel,[current]:v}});return <div className="modal-backdrop"><div className="modal reasoning-modal"><div className="modal-head"><div><h2>配置模型推理程度</h2><p>{provider.name||provider.id} · 左侧选择模型，右侧分别配置</p></div><button className="icon-button" onClick={close}><X size={18}/></button></div><div className="reason-layout"><div className="reason-models">{models.map(m=><button className={m===current?'selected':''} onClick={()=>setCurrent(m)} key={m}>{m}<small>{provider.reasoningByModel[m]?'已配置':'使用默认值'}</small></button>)}</div><div className="reason-settings"><h3>{current}</h3><span className="subhead">该模型支持的推理程度（可多选）</span><div className="checks">{levels.map(([id,label])=><label key={id}><input type="checkbox" checked={value.levels.includes(id)} onChange={e=>set({...value,levels:e.target.checked?[...value.levels,id]:value.levels.filter(x=>x!==id)})}/>{label}<small>{id}</small></label>)}</div><label className="default-reason">默认推理程度<select value={value.defaultLevel} onChange={e=>set({...value,defaultLevel:e.target.value})}><option value="auto">自动</option>{value.levels.map(id=><option key={id} value={id}>{levelName(id)}</option>)}</select></label></div></div><div className="modal-actions"><button className="primary" onClick={close}><Save size={16}/>应用全部设置</button></div></div></div>}

function Accounts({accounts,run,busy}:{accounts:Account[];run:(l:string,t:()=>Promise<unknown>)=>Promise<void>;busy:string}){const[adding,setAdding]=useState(false),[name,setName]=useState('');const add=async()=>{if(!name.trim())return;await run('新增账号',()=>invoke('add_account',{name:name.trim()}));setName('');setAdding(false)};return <section className="panel account-panel"><div className="section-head"><Title icon={<UserRound size={19}/>} title="OpenAI 账号" desc="每个账号拥有独立登录态，可从卡片直接启动 IDEA。"/><button className="primary" onClick={()=>setAdding(true)}><Plus size={16}/>新增 OpenAI 账号</button></div>{accounts.length===0?<div className="empty">尚未添加账号。新增后可进行普通 OAuth 登录，或导入已有 auth.json。</div>:<div className="account-grid">{accounts.map(a=><article className="account-card" key={a.id}><div className="account-top"><span className="avatar"><UserRound size={18}/></span><div><h3>{a.name}</h3><small className={a.loggedIn?'ok':'warn'}>{a.loggedIn?'● 已登录 · 独立账号':'● 尚未登录'}</small></div></div><div className="account-actions"><button className="outline" disabled={!!busy} onClick={()=>run('登录账号',()=>invoke('login_account',{id:a.id}))}><RefreshCw size={15}/>{a.loggedIn?'重新登录':'登录'}</button><button className="outline" disabled={!!busy} onClick={()=>run('导入认证',()=>invoke('import_account_auth',{id:a.id}))}><Download size={15}/>导入认证</button><button className="primary" disabled={!a.loggedIn||!!busy} onClick={()=>run('启动 IDEA',()=>invoke('launch_idea',{kind:'account',id:a.id}))}><Play size={15}/>启动 IDEA</button><button title="删除账号" className="danger icon-only" onClick={()=>{if(confirm(`删除账号“${a.name}”及其本地登录态？`))run('删除账号',()=>invoke('delete_account',{id:a.id}))}}><Trash2 size={15}/></button></div></article>)}</div>}{adding&&<div className="modal-backdrop" onClick={()=>setAdding(false)}><div className="modal account-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><h2>新增 OpenAI 账号</h2><p>名称只保存在本机，用来区分不同登录状态。</p></div><button className="icon-button" onClick={()=>setAdding(false)}><X size={18}/></button></div><label className="dialog-field">账号名称<input autoFocus value={name} placeholder="例如：个人账号、工作账号" onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add()}}/></label><div className="modal-actions"><button className="outline" onClick={()=>setAdding(false)}>取消</button><button className="primary" disabled={!name.trim()||!!busy} onClick={add}>添加账号</button></div></div></div>}</section>}
function Logs({logs,clear,run}:{logs:string[];clear:()=>void;run:(l:string,t:()=>Promise<unknown>)=>Promise<void>}){return <section className="log-section"><div className="log-toolbar"><span><i className="status-dot"/>实时日志</span><button onClick={()=>run('打开配置目录',()=>invoke('open_app_dir',{kind:'config'}))}><FolderOpen size={15}/>打开配置目录</button><button onClick={()=>run('打开日志目录',()=>invoke('open_app_dir',{kind:'logs'}))}><FileCog size={15}/>打开日志目录</button><button onClick={clear}><Trash2 size={15}/>清除界面日志</button></div><pre className="log-box">{logs.join('\n')}</pre></section>}
function Help({close}:{close:()=>void}){return <div className="modal-backdrop" onClick={close}><div className="modal help-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>配置与操作说明</h2><button className="icon-button" onClick={close}><X size={18}/></button></div><h3>第三方模型的顺序</h3><p>新建 Provider → 填写接口信息 → 保存配置 → 获取模型 → 配置各模型思考等级 → 测试连接 → 再次保存 → 完全退出 IDEA → 到“启动配置”启动。</p><h3>OpenAI 账号的顺序</h3><p>新增账号 → 点击登录完成普通 OAuth，或导入该账号的 Codex auth.json → 等待卡片自动刷新为“已登录” → 从卡片或启动页启动 IDEA。</p><h3>按钮何时使用</h3><p>“恢复备份”用于撤销最近一次第三方运行配置；“清理备份”按文件分别只保留最近 5 份。“打开配置目录”和“打开日志目录”用于排查问题；日志会脱敏 API Key 和令牌。</p><h3>隔离说明</h3><p>只有从本工具启动的 IDEA 才使用独立目录。第三方配置位于 %LOCALAPPDATA%\JetBrains\CodexIdeaHome，各 OpenAI 账号位于 CodexIdeaProfiles。普通方式打开 IDEA 和 Codex 桌面客户端均不受影响。</p><button className="primary" onClick={close}>知道了</button></div></div>}
